#!/bin/bash

#preps the first cockpit server
useradd rhel
echo "redhat" | passwd student --stdin
usermod -aG wheel rhel
echo "rhel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/rhel
chmod 0440 /etc/sudoers.d/rhel

#install enable and open firewall for cockpit
yum install cockpit-composer cockpit bash-completion -y
systemctl enable --now cockpit.socket
firewall-cmd --add-service=cockpit
firewall-cmd --add-service=cockpit --permanent

# Set dns=none for NetworkManager
sed -i -e "s/\[main\]/\[main\]\\ndns=none/" /etc/NetworkManager/NetworkManager.conf
systemctl restart NetworkManager

DNSIP=ADIPADDRESS
sed -i -e 's/# Generated by NetworkManager/$ADIPADDRESS/g" /etc/resolv.conf
