---
- hosts:  all
  become: yes
  vars:
    - ansible_python_interpreter: /usr/libexec/platform-python
  tasks:

    - name: get defaults
      include_vars:
        file: defaults/main.yml

    - name: Subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ subs_username }}"
        password: "{{ subs_pw }}"
        autosubscribe: false
        pool: "{{ subs_pool }}"

    - name: Enable required repositories
      rhsm_repository:
        name: "{{ enabled_repos_rhel8 }}"
        state: enabled

#    - name: Up it!
#      package: name=* state=latest

#    - name: install redhat nordics sa blog
#      include_role:
#        name: redhatnordicssa-blog
