---
- name: Prepare and configure the base
  hosts:  all
  gather_facts: no
  become: yes
  vars:
    - ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: get defaults
      include_vars:
        file: defaults/main.yml

    - name: Set hostname
      hostname:
        name: linux4win

    - name: Add the user 'rhel' as admin
      user:
        name: rhel
        password: '$6$pissomog$CMz8jyl/eY1Z8BvBK3248wD3IE.uzR1KY1ZqudgiqGCwfXNdc7CjbCaH.9pbJ8hB3hdoUbLXiIoNYq4.0jYW61'
        groups: wheel
        append: yes

    - name: Subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ subs_username }}"
        password: "{{ subs_pw }}"
        autosubscribe: false
        pool: "{{ subs_pool }}"

    - name: Enable required repositories
      rhsm_repository:
        name: "{{ enabled_repos_rhel8 }}"
        state: enabled

    - name: Install cockpit
      yum:
        name:
          - cockpit
        state: latest

    - name: Enable the cockpit service
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Open the firewall for cockpit
      firewalld:
        service: cockpit
        permanent: yes
        state: enabled
    - name: ensure realmd and all deps are installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - realmd
        - oddjob
        - oddjob-mkhomedir
        - sssd
        - adcli
        - samba-common-tools
    - name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        state: present
        no_extra_spaces: yes
        section: main
        option: dns
        value: none
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - reload NetworkManager
    - name: Add win domain controller as dns server
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^# Generated by NetworkManager'
        line: 'nameserver 10.0.1.6'
  handlers:
  - name: reload NetworkManager
    service:
      name: NetworkManager
      state: reloaded

- name: Install all needed parts for the workshop
  hosts:  all
  gather_facts: no
  become: yes
  vars:
    - ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
  - name: Prepare for lab2
    include_tasks: tasks/lab2.yml
  - name: Prepare for lab4
    include_tasks: tasks/lab4.yml
