---
- name: Install python3 and pip3
  yum:
    name: python3-pip
    state: present

- name: Install winrm dependencies
  pip:
    name: pywinrm

- name: Copy all installed site-packages from pip3 to platform-python
  command: cp -rf /usr/local/lib/python3.6/site-packages/* /usr/lib/python3.6/site-packages/