- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vars.yml

  tasks:
  - name: Ansible delete file wildcard
    find:
      paths: /tmp/
      patterns: "linux4win_*"
      use_regex: true
      file_type: directory
    register: wildcard_files_to_delete

  - name: Ansible remove file wildcard
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ wildcard_files_to_delete.files }}"


  - name: Terminate everything here
    amazon.aws.ec2_instance:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "{{ ec2_region }}"
      state: absent
      filters:
        instance-state-name: running
        "tag:Name": cockpit
        "tag:Name": rhel
        "tag:Name": winguest
        "tag:Name": ad


  - name: Remove the ec2 key pair
    amazon.aws.ec2_key:
      name: "{{ ec2_key }}"
      region: "{{ ec2_region }}"
      state: absent
