- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Get the public ips of the cockpit server
    amazon.aws.ec2_instance_info:
      aws_access_key: "{{ ec2_access_key | default(omit) }}"
      aws_secret_key: "{{ ec2_secret_key | default(omit) }}"
      region: "{{ ec2_region }}"
      filters:
        image-id: "{{ rhel_ami_id }}"
        instance-state-name: [ "pending", "running" ]
        "tag:Name": cockpit
    register: cockpit_status

  - name: All the data in cockpit_status
    debug:
      var: cockpit_status

#  - name: Loop over the dictionary
#    debug: msg="Key={{ public_ip_address }} value={{ item.value }}"
#    with_dict: "{{ cockpit_status.instances }}"


#  - name: Print the public ip of cockpit
#    debug:
#      msg: "{{cockpit_status.instances[0]['public_ip_address']}}"
